# Generated by Django 5.0.7 on 2026-06-04 14:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UploadBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('total_posts', models.IntegerField(default=0)),
                ('status', models.CharField(default='processing', max_length=32)),
                ('column_map', models.JSONField(blank=True, default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='IssueCluster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.IntegerField()),
                ('theme', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=100)),
                ('severity', models.CharField(max_length=32)),
                ('priority_score', models.FloatField(default=0)),
                ('suggested_action', models.TextField()),
                ('post_count', models.IntegerField(default=0)),
                ('examples', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('untouched', 'Untouched'), ('in_progress', 'In progress'), ('completed', 'Completed'), ('legacy', 'Legacy')], default='untouched', max_length=32)),
                ('progress_note', models.TextField(blank=True, default='')),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('relationship_type', models.CharField(blank=True, default='', max_length=64)),
                ('relationship_score', models.FloatField(default=0)),
                ('relationship_reason', models.TextField(blank=True, default='')),
                ('tree_depth', models.IntegerField(default=0)),
                ('tree_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('parent_cluster', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='api.issuecluster')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clusters', to='api.uploadbatch')),
            ],
        ),
        migrations.CreateModel(
            name='CommunityPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('cleaned_text', models.TextField()),
                ('created_at_raw', models.CharField(blank=True, default='', max_length=128)),
                ('user_id', models.CharField(blank=True, default='', max_length=255)),
                ('channel', models.CharField(blank=True, default='', max_length=255)),
                ('post_url', models.URLField(blank=True, default='')),
                ('report_count', models.IntegerField(default=0)),
                ('upvotes', models.IntegerField(default=0)),
                ('moderation_status', models.CharField(blank=True, default='', max_length=128)),
                ('embedding', models.JSONField(blank=True, default=list)),
                ('cluster_label', models.IntegerField(default=-1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='api.uploadbatch')),
            ],
        ),
        migrations.CreateModel(
            name='WeeklyReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('batch', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_report', to='api.uploadbatch')),
            ],
        ),
    ]
