# Generated by Django 5.0.7 on 2026-06-05 19:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auth_workspace_public_and_assignments'),
    ]

    operations = [
        migrations.AddField(
            model_name='issuecluster',
            name='status_confidence',
            field=models.FloatField(default=1.0),
        ),
        migrations.AddField(
            model_name='issuecluster',
            name='status_reason',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='issuecluster',
            name='status_source',
            field=models.CharField(choices=[('manual', 'Manual'), ('propagated', 'Propagated'), ('system', 'System')], default='manual', max_length=24),
        ),
        migrations.AddField(
            model_name='issuecluster',
            name='status_source_cluster',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='propagated_status_targets', to='api.issuecluster'),
        ),
        migrations.AlterField(
            model_name='issuecluster',
            name='status',
            field=models.CharField(choices=[('untouched', 'Untouched'), ('needs_review', 'Needs review'), ('confirmed', 'Confirmed'), ('planned', 'Planned'), ('in_progress', 'In progress'), ('partially_resolved', 'Partially resolved'), ('completed', 'Resolved'), ('blocked', 'Blocked'), ('wont_fix', "Won't fix"), ('not_affected', 'Not affected'), ('legacy', 'Legacy')], default='untouched', max_length=32),
        ),
    ]
