# Generated by Django 5.0.7 on 2026-06-06 17:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_issuecluster_status_confidence_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MainSpace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=180)),
                ('description', models.TextField(blank=True, default='')),
                ('join_code', models.CharField(db_index=True, max_length=32, unique=True)),
                ('is_discoverable', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_main_spaces', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.AddField(
            model_name='patterntree',
            name='main_space',
            field=models.ForeignKey(blank=True, help_text='Shared main/project space this tree belongs to. Workspace copies keep the same main_space.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trees', to='api.mainspace'),
        ),
        migrations.CreateModel(
            name='MainSpaceMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('owner', 'Owner'), ('admin', 'Admin'), ('member', 'Member')], default='member', max_length=20)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('main_space', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='api.mainspace')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='main_space_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['main_space_id', 'role', 'user_id'],
                'unique_together': {('main_space', 'user')},
            },
        ),
    ]
